//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMediaBrowser.MediaManagerWSRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MediaManagerWSRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/QueryMovies", ReplyAction="http://tempuri.org/IService1/QueryMoviesResponse")]
        System.Data.DataSet QueryMovies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/QueryMovies", ReplyAction="http://tempuri.org/IService1/QueryMoviesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> QueryMoviesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebMediaBrowser.MediaManagerWSRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebMediaBrowser.MediaManagerWSRef.IService1>, WebMediaBrowser.MediaManagerWSRef.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet QueryMovies() {
            return base.Channel.QueryMovies();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> QueryMoviesAsync() {
            return base.Channel.QueryMoviesAsync();
        }
    }
}
