//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMediaBrowser.UserValidationWSRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserWSDTO", Namespace="http://schemas.datacontract.org/2004/07/UserValidation")]
    [System.SerializableAttribute()]
    public partial class UserWSDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserValidationWSRef.UserValidationWS")]
    public interface UserValidationWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserValidationWS/ValidateUser", ReplyAction="http://tempuri.org/UserValidationWS/ValidateUserResponse")]
        WebMediaBrowser.UserValidationWSRef.UserWSDTO ValidateUser(WebMediaBrowser.UserValidationWSRef.UserWSDTO userObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserValidationWS/ValidateUser", ReplyAction="http://tempuri.org/UserValidationWS/ValidateUserResponse")]
        System.Threading.Tasks.Task<WebMediaBrowser.UserValidationWSRef.UserWSDTO> ValidateUserAsync(WebMediaBrowser.UserValidationWSRef.UserWSDTO userObject);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserValidationWSChannel : WebMediaBrowser.UserValidationWSRef.UserValidationWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserValidationWSClient : System.ServiceModel.ClientBase<WebMediaBrowser.UserValidationWSRef.UserValidationWS>, WebMediaBrowser.UserValidationWSRef.UserValidationWS {
        
        public UserValidationWSClient() {
        }
        
        public UserValidationWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserValidationWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserValidationWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserValidationWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebMediaBrowser.UserValidationWSRef.UserWSDTO ValidateUser(WebMediaBrowser.UserValidationWSRef.UserWSDTO userObject) {
            return base.Channel.ValidateUser(userObject);
        }
        
        public System.Threading.Tasks.Task<WebMediaBrowser.UserValidationWSRef.UserWSDTO> ValidateUserAsync(WebMediaBrowser.UserValidationWSRef.UserWSDTO userObject) {
            return base.Channel.ValidateUserAsync(userObject);
        }
    }
}
